# Generated by Django 5.1.2 on 2024-10-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wno', models.CharField(max_length=50)),
                ('from_field', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('cod', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('collected', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deficit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.CharField(blank=True, max_length=50, null=True)),
                ('received_by', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
